# Generated by Django 5.0.7 on 2024-11-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_casa_app', '0004_folder_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
