# Generated by Django 5.0.7 on 2024-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_casa_app', '0005_alter_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
            ],
        ),
    ]
