# Generated by Django 5.0.7 on 2024-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_casa_app', '0007_alter_booking_adults_alter_booking_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Regular price per night', max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Offer price per night', max_digits=10, null=True)),
            ],
        ),
    ]
